[DB+API+Component+Object]Label_feature:
jv-sep23-group4-D-ArtagnanAndCompany/task-management-app pull request #2
Opened 2024-01-11 18:12 UTC by DEz-1996

[DB]:
Add 10-add-constraints-labels-table.yaml
Add 11-insert-labels-labels-table.yaml
[API]:
Add LabelController.java
# Endpoints:
# create;
# getAll;
# update;
# delete.
[Component]:
LabelRepository.java
LabelMapper.java
Add LabelService.java
Add LabelServiceImpl.java
[Object]:
Add LabelRequestDto.java
Add LabelResponseDto.java

2024-01-11 19:46 UTC, RostyslavKuzmych requested changes
Just fix this mistakes

2024-01-11 19:46 UTC, RostyslavKuzmych commented on src/main/java/application/service/impl/LabelServiceImpl.java
> +        return labelMapper.toResponseDto(savedLabel);
return labelMapper.toResponseDto(labelRepository.save(labelMapper.toEntity(labelRequestDto);`

2024-01-11 19:46 UTC, RostyslavKuzmych commented on src/main/java/application/service/impl/LabelServiceImpl.java
> +        Label savedLabel = labelRepository.save(label);
You can just simplify that: 
labelMapper.toResponseDto(labelRepository.save(label)

2024-01-11 19:46 UTC, RostyslavKuzmych commented on src/main/resources/db/changelog/changes/11-insert-labels-labels-table.yaml
> +       id: insert-labels-labels-table
insert into*

2024-01-12 09:26 UTC, AgroFix approved these changes

2024-01-12 09:32 UTC, AgroFix approved these changes

2024-01-12 09:38 UTC, RostyslavKuzmych approved these changes

2024-01-12 09:39 UTC, merged