[DB+API]:  [DB]: added user to users table, and users-roles to users_roles table [API] Added AuthenticationController class
jv-sep23-group4-D-ArtagnanAndCompany/task-management-app pull request #3
Opened 2024-01-11 19:34 UTC by RostyslavKuzmych

2024-01-11 20:30 UTC, DEz-1996 requested changes
Some fixes are needed

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/java/application/security/CustomUserDetailsService.java
>                  -> new EntityNotFoundException(EXCEPTION + email));
rename constant EXCEPTION to CANT_FIND_BY_EMAIL

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/java/application/service/impl/UserServiceImpl.java
> +                                                            userRequestRegistrationDto) {
```suggestion
    public UserResponseRegistrationDto register(
            UserRequestRegistrationDto userRequestRegistrationDto) {

```

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/java/application/service/impl/UserServiceImpl.java
> +    private static final String EXCEPTION = "User with email %s is already authenticated";
```suggestion
    private static final String EMAIL_RESERVED= "User with email %s already exists";

```

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/java/application/service/impl/UserServiceImpl.java
> +                                                            userRequestRegistrationDto) {
```suggestion
    public UserResponseRegistrationDto register(
            UserRequestRegistrationDto userRequestRegistrationDto) {

```

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/resources/db/changelog/changes/11-add-user-to-users-table.yaml
> +                  value: 1
```suggestion

```

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/resources/db/changelog/changes/12-add-users_roles-to-users_roles-table.yaml
> +                  value: 1
```suggestion
                  valueComputed: (SELECT id FROM users WHERE email='alice@gmail.com')

```

2024-01-11 20:30 UTC, DEz-1996 commented on src/main/resources/db/changelog/changes/12-add-users_roles-to-users_roles-table.yaml
> +                  value: 1
```suggestion
                  valueComputed: (SELECT id FROM roles WHERE name='ADMIN')

```

2024-01-12 07:46 UTC, AgroFix approved these changes

2024-01-12 07:46 UTC, AgroFix commented on src/main/java/application/model/User.java
> +    @Getter
If I'm not mistaken, if you have @Data, you don't need @Getter

2024-01-12 07:52 UTC, merged